# Generated by Django 4.1.6 on 2023-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="source",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
