# Generated by Django 4.1.6 on 2023-02-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
