# Generated by Django 4.1.6 on 2023-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_income_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("GROCERIES", "Grocery"),
                    ("RENT", "Rent"),
                    ("OTHER", "Other"),
                    ("UTILITIES", "Utilities"),
                    {"TRANSPORTATION", "Transportation"},
                    ("CLOTHING", "Clothing"),
                    ("VACATION", "Vacation"),
                    ("GIFTS", "Gifts"),
                    ("MEDICAL", "Medical"),
                    ("INSURANCE", "Insurance"),
                    ("EDUCATION", "Education"),
                    ("SAVINGS", "Savings"),
                    ("MISCELLANEOUS", "Miscellaneous"),
                ],
                default="OTHER",
                max_length=15,
            ),
        ),
    ]
